#!/bin/bash

function check() {
    phpcs $1
    phpmd $1 text 'cleancode,codesize,controversial,design,naming,unusedcode' --exclude=vendor
    phpstan analyze --level=7 $1
    phpcpd --fuzzy --exclude vendor $1
}

if [ $# -eq 0 ]
	then
        check ./
        exit 1
fi

while getopts "mp:" opt
	do
	case $opt in
        m)
            for file in $(git ls-files -om --exclude-standard)
                do
                    check $file
                done

            exit 1
            ;;
        p)
            check $OPTARG
            ;;
	esac
done
