#!/bin/bash

function check() {
    checkFileExistence phpcs.xml
    phpcs $1
    checkFileExistence phpmd.xml
    phpmd $1 text phpmd.xml
    checkFileExistence phpstan.neon
    phpstan analyze --level=7 $1
    checkFileExistence phpcpd.xml
    phpcpd --fuzzy --exclude vendor $1
}

function checkFileExistence() {
    if [ ! -f $1 ]; then
        echo "File $1 not found!"
        exit 1
    fi
}

if [ $# -eq 0 ]
	then
        check ./
        exit 1
fi

while getopts "mp:" opt
	do
	case $opt in
        m)
            for file in $(git ls-files -om --exclude-standard)
                do
                    check $file
                done

            exit 1
            ;;
        p)
            check $OPTARG
            ;;
	esac
done
