FROM php:8.3-cli-alpine as phpstan

RUN apk add --no-cache --upgrade \
    wget \
    bash \
    make \
    git \
    patch \
    yq

COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN git clone https://github.com/phpstan/phpstan-src.git /phpstan-src
WORKDIR /phpstan-src
RUN cd /phpstan-src  \
    && composer install \
    && composer require phpstan/phpstan-doctrine \
    && composer require phpstan/phpstan-symfony \
    && composer require phpstan/phpstan-phpunit \
    && cd compiler \
    && composer install \
    && php bin/prepare
#    && cd build \
#    && box.phar compile
