#!/usr/bin/env php
<?php

$xml = simplexml_load_file('phpcpd.xml');

$fuzzy = (string) $xml->fuzzy == 'true' ? '--fuzzy' : '';
$minLines = (string) $xml->minLines;
$minTokens = (string) $xml->minTokens;
$excludes = $xml->exclude->path;

$exclude = '';
foreach ($excludes as $excludeEntry) {
    $exclude .= '--exclude='.$excludeEntry.' ';
}

$command = "vendor/bin/phpcpd $exclude $fuzzy --min-lines=$minLines --min-tokens=$minTokens " . $argv[1];

exec($command, $output);
foreach ($output as $line) {
    echo $line . PHP_EOL;
}
